[project]
name = "hw-guide-with-o3-mini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai>=1.88.0",
    "pdfplumber>=0.11.7",
    "pytest>=8.4.1",
    "pyyaml>=6.0.2",
]
